from lib import *
fn = "apspanish_unit1"

print("Answer all questions in the masculine form if both are possible.")
questions = Game([], fn)
questions.worst_hole = -1


questions.add(Question.FRQ("the present (time) ","la actualidad",                            filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("godson/goddaughter","el ahijado",                                filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("ancestor ","el antepasado",                                      filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("last name/ family name ","el apellido",                          filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("contribution ","el aporte",                                      filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("tie, bond ","la atadura",                                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("brother-in-law/sister in law ","el cuñado",                      filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("duty, chore, responsibility ","el deber",                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("core idea ","el eje",                                            filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("pregnancy ","el embarazo",                                       filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("trick, lie, hoax ","el engaño",                                  filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("training ","el entrenamiento",                                   filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("time period, stage ","la etapa",                                 filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("evocation, memory ","la evocación",                              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("line ","la fila",                                                filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("strengthening ","el fortalecimiento",                            filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("expense ","el gasto",                                            filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("heritage, inheritance, heredity ","la herencia",                 filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("mortgage ","la hipoteca",                                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("home ","el hogar",                                               filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("tribute, homage ","el homenaje",                                 filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("orphan (m/f)","el huérfano",                                     filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("godfather/godmother ","el padrino",                              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("love of your life, other half, soulmate ","la media naranja",    filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("the media ","los medios",                                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("engagement ","el noviazgo",                                      filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("homeland, fatherland, motherland ","la patria",                  filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("average ","el promedio",                                         filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("challenge, difficulty ","el reto",                               filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("wisdom ","la sabiduría",                                         filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("sovereignty ","la soberanía",                                    filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("soldier ","el soldado",                                          filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("rate (noun)","la tasa",                                          filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("link, connection ","el vínculo",                                 filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("widow, widower","el viudo",                                      filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("current ","actual",                                              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("independent of one's parents ","emancipado",                     filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("family (adjective) ","familiar",                                 filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("single/not married ","soltero",                                  filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to praise ","alabar",                                            filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to distance yourself or move away from ","alejarse de",          filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to unite with, form alliance with ","aliarse con",               filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to approve or to pass (a test) ","aprobar       ",               filtered_equals(nest(stripped, lowercased)), end_hint="o->ue"))
questions.add(Question.FRQ("to take advantage of a situation ","aprovecharse",               filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to defeat ","derrotar",                                          filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to educate ","educar",                                           filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to be emotional or excited ","emocionar",                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to guide ","guiar",                                              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to sponsor ","patrocinar",                                       filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to complain ","quejarse",                                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to recover, get well ","recuperar",                              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to stand out, to emphasize ","resaltar",                         filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to support or sustain ","sostener",                              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("currently ","actualmente",                                       filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("with respect to ","con respeto a",                               filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to miss (#1) ","echar de menos",                                 filtered_equals(nest(stripped, lowercased))))
# questions.add(Question.FRQ("to miss (#2)","extrañar",                                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to make an offering to ","en ofrenda a",                         filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("well behaved ","bien nacido",                                    filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("old age ","la tercera edad",                                     filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to make decisions ","tomar decisiones",                          filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("a hermit ","el ermitaño",                                        filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to embody, personify ","encamar",                                filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to move to another place or transfer ","trasladar",              filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to pass away ","fallecer",                                       filtered_equals(nest(stripped, lowercased))))
questions.add(Question.FRQ("to pray ","rezar",                                               filtered_equals(nest(stripped, lowercased))))

questions.run()